### ISSUE TITLE
[BUG]🐛 - Navigation is called twice

### ISSUE THREAD

**Issue by Bartozo** [Thelouras58/PatternLock-BrainGames#1]
### Step 1: Describe your environment

  * Android device: S21+
  * Android OS version: Android 12
  * App Version: 1.1.0
  
### Step 2: Describe the problem:
Navigation can be called multiple times, which leads to opening many screens. This can be done very easily, by just clicking on a button few times in a row. You can also check the video which shows this issue. 

https://user-images.githubusercontent.com/10104462/177762988-fffd910d-b474-4778-88d6-41ba3ba99ac7.mp4

#### Steps to reproduce:

  1.  Go to the menu screen where you can see the elevated buttons.
  2. Try to tap a button twice in a short moment.
  3. Navigation will be called twice or more.  
  4. Navigation stack now will have multiple same screens.  5. 
#### Observed Results:

  * I think this might be issue related to the transition's animation. That's why it possible to click button few times and get multiple same screens in navigation's stack.
  
#### Expected Results:

  * I expect that by clicking button I won't be able to open same screen twice.

**Comment by Thelouras58** [comment]
Done! It will be included in version 1.2.0

thanks @Bartozo
