### ISSUE TITLE
[BUG]🐛 - Windows insets are not correct, which leads to black status bar.

### ISSUE THREAD

**Issue by Bartozo** [Thelouras58/PatternLock-BrainGames#2]
### Step 1: Describe your environment

  * Android device: S21+
  * Android OS version: Android 12
  * App Version: 1.1.0
  
### Step 2: Describe the problem:
In some screens there's black bar visible on the top of the screen. Look's like the background insets, are not supporting the devices with cutout in display. 

![291651886_556831262777313_2292953678577725395_n](https://user-images.githubusercontent.com/10104462/177764769-f687c766-c08c-477f-987e-ba3e6d2eb42c.jpg)
![291788222_408851174619923_3866787154907827066_n](https://user-images.githubusercontent.com/10104462/177764777-9c2630a2-b1fb-47dc-ad5a-c566d9ff3fe4.jpg)

#### Steps to reproduce:

  1.  Install app on a device with display cutout.
  2. Open game screen.
  3. Black status bar will be visible on the screen.

#### Observed Results:

  * This is probably only visible on devices with display cutout.
  
#### Expected Results:

  * I expect that background screen should take full size of my screen. You can read more about supporting these here:
https://developer.android.com/guide/topics/display-cutout

**Comment by Thelouras58** [comment]
Fixed - it will deployed w/ version 1.2.0

Thanks @Bartozo
